version: '3.3'

services:
  api:
    container_name: toolchain-api
    restart: always
    build:
      context: .
      args:
        DD_AGENT_MAJOR_VERSION: ${DD_AGENT_MAJOR_VERSION}
        DD_API_KEY: ${DD_API_KEY}
    ports:
      - '3000:3000'

